### ISSUE TITLE
BCDBFS Links

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtech/jumpscaleX_core#108]
The idea is to be able to share files from your BCDB with other 3Bots without copying the data.

## Use case
- *3bot A* wants to share file */myfile.txt* with *3bot B*
- *3bot A* will send the file link to *3bot B*
- *3bot B* will store the link in the specified directory (in this case it will be "/")
- *3bot B* now has basic metadata of the file/dir and some info pointing to *3bot A*
- when *3bot B* tries to read the file/dir content it will request it from *3bot A*
![image](https://user-images.githubusercontent.com/5163693/65607379-bb39b100-dfac-11e9-85d6-7f74376d1335.png)

## Prerequisites 
- [ ] Threebot client to be able to comunicate with another 3bot given only the 3bot id
- [ ] Address book and the communication layer should be working well.

## tasks
- [ ] implement Link model 
- [ ] add Links support to bcdbfs (reading from another 3bot)
- [ ] implement actor to receive and send a link

**Comment by despiegk** [comment]
check with kristof for client/server rpc model

**Comment by rkhamis** [comment]
requires threefoldtech/jumpscalex_threebot#50

**Comment by xmonader** [comment]
not valid anymore
