### ISSUE TITLE
rework installation documentation

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#2]
## issue

- so much duplication now 
- the markdown is weird at least, should not have intended spaces then lists

## todo

- [x] no mo duplication
- [x] more simple, jsx tools is doing +- all, there is too much in docu
- [x] simplify markdown, lets only use simple things

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/63648646-16208400-c733-11e9-8fcb-9f6fe5df8df5.png)
too complicated

never space space ... then list
or - ####
...

**Comment by zaibon** [comment]
Indeed this is really not proper markdown. Like any other code markdown also has specification. Anyone writing markdown should use a linter to make sure to write properly formatted documents.
There is a linter for any editor out there, let's use it please.

**Comment by waleedhammam** [comment]
Simplified docs [Removed duplication, Simplified markdown] 
Commit: https://github.com/threefoldtech/jumpscaleX_core/commit/d6ef118b1fa2843cced1ebc6839fff5776f9fac9 
Docs at: https://github.com/threefoldtech/jumpscaleX_core/tree/master/docs/Installation
